name: Test

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci --install-links
      - name: Run Jest
        run: npm run jest
      - uses: codecov/codecov-action@v3
        with:
          flags: unit
          files: "**/jest/coverage*.json"
      - name: Run Playwright
        run: xvfb-run npm run playwright
      - uses: codecov/codecov-action@v3
        with:
          flags: ui
          files: "**/playwright/coverage*.json"