name: Test

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    name: OverlayScrollbars Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run Jest
        run: npm run jest
      - name: Run Playwright
        run: xvfb-run npm run playwright
      - name: Upload Jest Coverage
        uses: codecov/codecov-action@v3
        with:
          flags: overlayscrollbars,unit
          files: "**/overlayscrollbars/**/jest/coverage*.json"
      - name: Upload Playwright Coverage
        uses: codecov/codecov-action@v3
        with:
          flags: overlayscrollbars,ui
          files: "**/overlayscrollbars/**/playwright/coverage*.json"
